// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: category.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories ("name")
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCategory, id)
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, name, entries, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryById(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, entries, created_at, updated_at
FROM categories
WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryEntries = `-- name: GetCategoryEntries :one
SELECT entries
FROM categories
WHERE name = $1
`

func (q *Queries) GetCategoryEntries(ctx context.Context, name string) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getCategoryEntries, name)
	var entries pgtype.Int4
	err := row.Scan(&entries)
	return entries, err
}
