// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: habit.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (
    "name",
    "category",
    "description",
    "frequency",
    "start_date",
    "target_date",
    "priority"
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateHabitParams struct {
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
	Frequency   []Weekday   `json:"frequency"`
	StartDate   pgtype.Date `json:"start_date"`
	TargetDate  pgtype.Date `json:"target_date"`
	Priority    int16       `json:"priority"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Frequency,
		arg.StartDate,
		arg.TargetDate,
		arg.Priority,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteHabit = `-- name: DeleteHabit :execresult
DELETE FROM habits
WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteHabit, id)
}

const getHabitById = `-- name: GetHabitById :one
SELECT id, name, category, description, frequency, start_date, target_date, priority, created_at, updated_at FROM habits WHERE id = $1
`

func (q *Queries) GetHabitById(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabitById, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.TargetDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHabitByName = `-- name: GetHabitByName :one
SELECT id, name, category, description, frequency, start_date, target_date, priority, created_at, updated_at FROM habits WHERE name = $1
`

func (q *Queries) GetHabitByName(ctx context.Context, name string) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabitByName, name)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.TargetDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET
    name = COALESCE($2, name),
    category = COALESCE($3, category),
    description = COALESCE($4, description),
    frequency = COALESCE($5, frequency),
    start_date = COALESCE($6, start_date),
    target_date = COALESCE($7, target_date),
    priority = COALESCE($8, priority),
    updated_at = NOW()
WHERE id = $1
RETURNING
id,
name,
category,
description,
frequency,
start_date,
target_date,
priority,
created_at,
updated_at
`

type UpdateHabitParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
	Frequency   []Weekday   `json:"frequency"`
	StartDate   pgtype.Date `json:"start_date"`
	TargetDate  pgtype.Date `json:"target_date"`
	Priority    int16       `json:"priority"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Frequency,
		arg.StartDate,
		arg.TargetDate,
		arg.Priority,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.TargetDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
