// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package mysqlstore

import (
	"database/sql"
)

type User struct {
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        []byte       `json:"id"`
}
